### ISSUE TITLE
Regexp properties can't be passed as strings.

### ISSUE THREAD

**Issue by ghost** [x-formation/pulsekit#7]
This is the case at least for --project property. It causes problems when, valid project name is invalid regex, for example: "C++ - Unittest":
pulsecli --patch f.diff --project "C++ Unittest" personal
Verify if other properties have the same issue and fix this, using result of regex instead of regex itself.

**Comment by aquemy** [comment]
Fixed by the squashed commit: https://github.com/x-formation/pulsekit/commit/d90b5ee1ff29ac9590a24ace30c529c1cd2dfe5e
